# Generated by Django 5.0.1 on 2024-02-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_path', models.CharField(max_length=255)),
                ('input_data', models.TextField()),
                ('result', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='processing', max_length=50)),
            ],
        ),
    ]
